Repository GSSoC-Flow/WardhaMetroFLow, pull requests merged in 2025-08, with the labels that each got.

#34 Rename CODE_OF_CONDUCT.md to code_of_conduct.md
  code_of_conduct.md
Labels: level 1

#49 Revamp Admin Portal UI & Add Analytical Plots (Fixes #9, #10, #46)
  frontend/Admin.html
  frontend/admin-script.js
  frontend/admin-styles.css
Labels: GSSoC'25, level 3

#62 Resolves ISSUE #55
  frontend/Admin.html
  frontend/admin-script.js
  frontend/admin-styles.css
  frontend/passenger.html
Labels: level 2, GSSoC'25

#61 Added new stations in the passenger station selection option and improved the way stations are selected.
  frontend/admin-styles.css
  frontend/passenger.html
Labels: GSSoC'25, level 3

#65 feat: Implement Custom Animated Trail Cursor (Closes #64)
  frontend/Admin.html
  frontend/common/cursor.css
  frontend/common/cursor.js
  frontend/passenger-script.js
  frontend/passenger-styles.css
  frontend/passenger.html
Labels: GSSoC'25, level 3

#79 Fix: Inconsistent Navigation Between Top and Bottom Menu Bars in Admin View (fixes #76)
  frontend/Admin.html
  frontend/package-lock.json
Labels: GSSoC'25, level 3

#94 Fix:Duplication of navbar,clean ui and ux,added some functionalities in ADMIN page->issue #90
  frontend/Admin.html
  frontend/admin-script.js
  frontend/admin-styles.css
Labels: GSSoC'25, level 3

#91 Remove React.js from tech stack section
  README.md
Labels: level 2, GSSoC'25

#97 Fixed the Navbar theme
  frontend/.Rhistory
  frontend/passenger.css
Labels: GSSoC'25, level 1
